//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Artist
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Artist()
    {
        this.ShowDetails = new HashSet<ShowDetail>();
        this.Fans = new HashSet<Fan>();
    }

    public int ArtistKey { get; set; }
    public string ArtistName { get; set; }
    public string ArtistEmail { get; set; }
    public string ArtistWebPage { get; set; }
    public Nullable<System.DateTime> ArtistDateEntered { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ShowDetail> ShowDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Fan> Fans { get; set; }
}

public partial class Fan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Fan()
    {
        this.FanLogins = new HashSet<FanLogin>();
        this.Artists = new HashSet<Artist>();
    }

    public int FanKey { get; set; }
    public string FanName { get; set; }
    public string FanEmail { get; set; }
    public Nullable<System.DateTime> FanDateEntered { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FanLogin> FanLogins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Artist> Artists { get; set; }
}

public partial class FanLogin
{
    public int FanLoginKey { get; set; }
    public Nullable<int> FanKey { get; set; }
    public string FanLoginUserName { get; set; }
    public string FanLoginPasswordPlain { get; set; }
    public int FanLoginRandom { get; set; }
    public byte[] FanLoginHashed { get; set; }
    public Nullable<System.DateTime> FanLoginDateAdded { get; set; }

    public virtual Fan Fan { get; set; }
}

public partial class LoginHistory
{
    public int LoginHistorykey { get; set; }
    public string UserName { get; set; }
    public Nullable<System.DateTime> LoginHistoryDateTime { get; set; }
}

public partial class Show
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Show()
    {
        this.ShowDetails = new HashSet<ShowDetail>();
    }

    public int ShowKey { get; set; }
    public string ShowName { get; set; }
    public Nullable<int> VenueKey { get; set; }
    public System.DateTime ShowDate { get; set; }
    public System.TimeSpan ShowTime { get; set; }
    public string ShowTicketInfo { get; set; }
    public Nullable<System.DateTime> ShowDateEntered { get; set; }

    public virtual Venue Venue { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ShowDetail> ShowDetails { get; set; }
}

public partial class ShowDetail
{
    public int ShowDetailKey { get; set; }
    public Nullable<int> ShowKey { get; set; }
    public Nullable<int> ArtistKey { get; set; }
    public System.TimeSpan ShowDetailArtistStartTime { get; set; }
    public string ShowDetailAdditional { get; set; }

    public virtual Artist Artist { get; set; }
    public virtual Show Show { get; set; }
}

public partial class Venue
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Venue()
    {
        this.Shows = new HashSet<Show>();
        this.VenueLogins = new HashSet<VenueLogin>();
    }

    public int VenueKey { get; set; }
    public string VenueName { get; set; }
    public string VenueAddress { get; set; }
    public string VenueCity { get; set; }
    public string VenueState { get; set; }
    public string VenueZipCode { get; set; }
    public string VenuePhone { get; set; }
    public string VenueEmail { get; set; }
    public string VenueWebPage { get; set; }
    public Nullable<int> VenueAgeRestriction { get; set; }
    public Nullable<System.DateTime> VenueDateAdded { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Show> Shows { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VenueLogin> VenueLogins { get; set; }
}

public partial class VenueLogin
{
    public int VenueLoginKey { get; set; }
    public Nullable<int> VenueKey { get; set; }
    public string VenueLoginUserName { get; set; }
    public string VenueLoginPasswordPlain { get; set; }
    public int VenueLoginRandom { get; set; }
    public byte[] VenueLoginHashed { get; set; }
    public Nullable<System.DateTime> VenueLoginDateAdded { get; set; }

    public virtual Venue Venue { get; set; }
}
